### ISSUE TITLE
Is there a way to save invoice to pdf?

### ISSUE THREAD

**Issue by Casterke** [zoparga/laravel-szamlazzhu#2]
Is there a way to query and save the invoice to pdf?

**Comment by zoparga** [comment]
Hey there,

You can set it up in the provided config file, to auto_save the invoices and which disk should it use.

**Comment by Casterke** [comment]
> Hey there,
> 
> You can set it up in the provided config file, to auto_save the invoices and which disk should it use.

First of all thanks for the reply!
Yes I see that auto_save is saving when "creating" the invoice, but what if the invoice is already created and I would like the query/save it?

**Comment by zoparga** [comment]
Yeah, that function is not exists yet sadly. 
I already thought about it. To be honest I didn't have the free time to implement it, but it is on my to-do list :)

Until that, you can open a Pull Request with that function and I will be happy to check it out :)

**Comment by Casterke** [comment]
> Yeah, that function is not exists yet sadly. I already thought about it. To be honest I didn't have the free time to implement it, but it is on my to-do list :)
> 
> Until that, you can open a Pull Request with that function and I will be happy to check it out :)

Yes, I'm on the same boat as you I was also glad that this repo exists :)
If I have time in the near future I will create PR
Thanks have a nice day! :)
