### ISSUE TITLE
Call to undefined method zoparga\SzamlazzHu\Client\Client::taxSubjects()

### ISSUE THREAD

**Issue by gergoo** [zoparga/laravel-szamlazzhu#4]
Szia!

Az augusztus 11-én elfogadott pull request (link: https://github.com/zoparga/laravel-szamlazzhu/commit/31294b69074c155fd0ddfff9742183ae1267ef87) után a csatolt képen látható hibát kaptam:

<img width="1403" alt="image" src="https://github.com/zoparga/laravel-szamlazzhu/assets/2934385/9d2b6439-913d-4b07-8a05-d920a9d3f558">

A javítást előre is köszönjük!

Üdv!

**Comment by zoparga** [comment]
Köszi a jelzést!
Amint lesz időm javítom.

Ha sürgős & még nem lenne fenn a javítás, akkor kérlek dobj egy PR-t és megnézem majd.
