### ISSUE TITLE
Support API Agent 2.10.16+

### ISSUE THREAD

**Issue by gergoo** [zoparga/laravel-szamlazzhu#6]
Szia!

Egy olyan értesítés érkezett a szamlazz.hu-tól, miszerint 2024 januárjától már csak a 2.10.16+ API Agent-et fog támogatni a szolgáltató.

Az a kérdés merült föl ezzel kapcsolatban, hogy ennek a támogatása megoldott-e aktuálisan zoparga/laravel-szamlazzhu package aktuális verziójában, vagy igényel-e bármilyen módosítást.

A hivatalos changelog alapján az alábbiak változtak az adott időpontokban, adott verziókban: https://docs.szamlazz.hu/changelog.html

A választ előre is köszönjük!

Üdv!

**Comment by zoparga** [comment]
Szia,

Köszi, hogy jelezted!

A jelenlegi nem támogatja aktuálisan. Jelenleg magánéleti teendők/problémák vannak sajnos, így emiatt ígérni sem tudom, hogy pár héten belül elkészül.

Januárig azonban vállalható teljesen.
Nyitva hagyom az issue-t pont emiatt, hogy ez el is tudjon készülni.

Amennyiben elkészül, úgyis új verzió lép majd életbe, így remélhetőleg a frissítésen kívül más teendő nem lesz. Bár látatlanban nem merem ígérni ezt sem.

Természetesen a frissítést tartalmazó PR-t szívesen fogadok.

További szép napot!

**Comment by merobal** [comment]
Sziasztok!
Anno mi is csináltunk egy forkot a Redmentával, mert kellett pár javítás asap. Viszont nyitottak vagyunk besegíteni, csinálhatnánk egy közös hivatalos verziót, hogy könnyebb legyen közösen és gyorsabban egy verziót fenntartani.
Te/ti tudtok még másokról akik csináltak forkot, vagy elég ha pl. mi nyitunk ide egy PR-t?
(Ha decemberben találunk időt lehet be tudjuk vállalni a frissítést is a csapattal.)

**Comment by zoparga** [comment]
Szia,

Az igazat megvallva nem tudok másról.
Ha forkolta is valaki, akkor azt nem jelezte. 

Ha ide nyitjátok a PR-okat, akkor részemről az is működhet.
Nyilván, ha lesz időm akkor én is tolom a frissítéseket.

**Comment by merobal** [comment]
Megnéztem a Számlázz.hu PHP API Agentet, és ez a Laraveles lib nem használja azt, hanem közvetlenül kommunikál az XML API-val. @gergoo te hol találkoztál ezzel az értesítéssel? Próbálom kikutatni, hogy miért küldhették azt az értesítést, esetleg az XML schema-ban van-e olyan változás, amit nekünk is le kellene követnünk?

**Comment by zoparga** [comment]
Az issue-t lezárom, mivel a támogatás (azóta is) megoldott, hibáról nem tudok.
