### ISSUE TITLE
Technológiai változások 2024

### ISSUE THREAD

**Issue by merobal** [zoparga/laravel-szamlazzhu#8]
Szia!

A számlázz.hu hamarosan bevezet pár újdonságot: https://tudastar.szamlazz.hu/gyik/technologiai-valtozasok-2024

Úgy tűnik, hogy a #6 issue alatt jelzett dolgot végül nem kellett kezelni, azóta is működik, viszont nem tudom, hogy a header módosítások aktuálisak-e. A cert módosításnál pedig passz, ahogy nézem jelenleg a sima http protokollon keresztül hívja a lib az API-t. (Esetleg érdemes lenne azt is tesztelni https kapcsolaton keresztül?)

@zoparga neked lesz kapacitásod / szabad időd az elkövetkező hetekben megnézni ezeket a kérdéseket?

Üdv!

**Comment by zoparga** [comment]
Szia,

Hétvégén megnézem mi a helyzet és itt visszajelzek!

Köszi a jelzést!

További szép napot & jó munkát!

**Comment by zoparga** [comment]
Szia @merobal,

Jelenleg a http -> https változtatás csak használhatatlanná teszi a csomagot.

Headerhez kapcsolódó részek pedig nincsenek is ilyen exakt módon vizsgálva a csomagban, ahogy az eredeti lib-ben. Van valami teszt elérés szerinted, ahol a lehetne tesztelni a május 10 utáni állapotot?

**Comment by merobal** [comment]
Beszéltem az ügyfélszolgálattal, és ezeket a válaszokat kaptam:

>Az éles környezet átállása május 10-én történik.
>Nincs olyan nyilvános teszt környezet, ahol ezt előre tesztelni lehetséges.
>Leghamarabb 11-én hajnalban lehetséges tesztelni a kapcsolatot. Illetve csak a https csatorna lesz elérhető.

Addig annyit tudunk tesztelni, hogy a lib egy GET hívást küld a https://certtest.szamlazz.hu/ oldalra és megnézzük, hogy az működik-e. Viszont ezek alapján kell egy cleanup a mostani cert kezelésre, és fixen át kell állítani https-re az API hívásokat.

**Comment by zoparga** [comment]
Köszi az utánajárást!

Az az oldal működik, de ahogy írja is a felhívás, csak arra szolgál, hogy látható a Let's Encrypt által elkészített tanusítvány.

A custom cert hozzáadást kivettem a következő PR-ban látható, ezt nézzétek meg kérlek:
https://github.com/zoparga/laravel-szamlazzhu/pull/9

Az API hívások egyébként is https-en keresztül mentek, ha csak nem módosítottatok rajta:
https://github.com/zoparga/laravel-szamlazzhu/blob/521a256f53b2e5703025991ed9025311612201a2/config/config.php#L47

A kódban megtalálható sima http-t használó `http://www.szamlazz.hu/` részek, az XML küldésnél vannak. Erre írtam, hogy ha módosítom, akkor fixen lehal az egész.

**Comment by zoparga** [comment]
Szia @merobal ,

Kitettem az előző PR-t, azonban anélkül is működnie kell továbbra is. 
Ahogy a fentebbi commentben is jeleztem, a base uri biztonságos, `https` kapcsolaton keresztül kommunikált eddig is.

A self certificate option-t kivettem, a teszteket rendeztem.

Az issue-t így zárom, mivel a számla generálással nincs gond.

**Comment by merobal** [comment]
Szuper, köszi! Meg tudom erősíteni, hogy közben nekünk is működött tovább a meglévő verzió. Köszi a frissítéseket!
